# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: b80a92d
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
github_repo_name: boilerdata
project_description: Data processing pipeline for a nucleate pool boiling apparatus.
project_email: blake.naccarato@gmail.com
project_name: boilerdata
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.10'
year_of_project_creation: 2022
