# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d32bfe1
_src_path: gh:blakeNaccarato/copier-python
actions_runner: windows-latest
github_repo_name: boilerdata
include_funding: true
override: true
override_codecov: false
override_coveragerc: false
override_env: false
override_flake8: false
override_gitattributes: false
override_gitignore: false
override_isort: false
override_markdownlint: false
override_precommit: false
override_pyrightconfig: false
override_pytest: false
override_sourcery: false
override_update: false
override_vscode_extensions: false
override_vscode_launch: true
override_vscode_settings: true
override_vscode_tasks: true
project_email: blake.naccarato+boilerdata@gmail.com
project_name: boilerdata
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.10'
use_dvc: true
year_of_project_creation: 2022
