# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: fbdd2ae
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: boilerdata
include_funding: true
override: true
override_coveragerc: false
override_env: false
override_flake8: false
override_gitattributes: false
override_pyrightconfig: false
override_pytest: false
override_sourcery: false
override_vscode_extensions: false
override_vscode_launch: true
override_vscode_settings: false
override_vscode_tasks: false
project_email: blake.naccarato+boilerdata@gmail.com
project_name: boilerdata
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.10'
year_of_project_creation: 2022
