stages:
  schema:
    cmd: "python -m boilerdata.stages.schema"
    deps:
      - "src/boilerdata/stages/schema.py"
      - "src/boilerdata/models/axes.py"
      - "src/boilerdata/models/common.py"
      - "src/boilerdata/models/project.py"
      - "src/boilerdata/models/trials.py"
    outs:
      - "data/schema"
      # # DVC deletes outs before generating. Deleting this file breaks the stage.
      # - "src/boilerdata/models/axes_enum.py"

  runs:
    cmd: "python -m boilerdata.stages.runs"
    deps:
      - "src/boilerdata"
      - "data/curves"
      - "data/schema"
    outs: ["data/runs"]

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    params:
      - "config/axes.yaml":
      - "config/project.yaml":
      - "config/trials.yaml":
    deps:
      - "src/boilerdata"
      - "data/schema"
      - "data/runs"
    outs: ["data/results"]

  originlab:
    cmd: "python -m boilerdata.stages.originlab"
    deps:
      - "src/boilerdata"
      - "data/plotter"
      - "data/results"
    plots: ["data/plots/lit_.png"]
