stages:
  axes:
    cmd: "python -m boilerdata.stages.axes"
    deps:
      - "${project_paths.stage_axes}"
      - "${project_paths.requirements}"
      - "${project_paths.dev_requirements}"
      - "${project_paths.config}/axes.yaml"
      - "${project_paths.models}"
    outs:
      - "${dirs.axes}"

  modelfun:
    cmd: "papermill ${project_paths.stage_modelfun} NUL"
    deps:
      - "${project_paths.stage_modelfun}"
      - "${dirs.axes}"
    outs:
      - "${dirs.modelfun}"
    params:
      - "params.model_inputs"
      - "params.model_params"
      - "params.fixed_params"

  runs:
    cmd: "python -m boilerdata.stages.prep.runs"
    deps:
      - "${project_paths.stage_runs}"
      - "${dirs.axes}"
      - "${dirs.trials}"
    outs:
      - "${dirs.runs}"
    params:
      - "params.records_to_average"

  parse_benchmarks:
    cmd: "python -m boilerdata.stages.prep.parse_benchmarks"
    deps:
      - "${project_paths.stage_parse_benchmarks}"
      - "${dirs.axes}"
      - "${dirs.benchmarks}"
    outs:
      - "${dirs.benchmarks_parsed}"

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    deps:
      - "${project_paths.stage_pipeline}"
      - "${dirs.modelfun}"
      - "${dirs.runs}"
      - "${dirs.benchmarks_parsed}"
      - "${project_paths.validation}"
    outs:
      - "${dirs.results}"
    params:
      - "params.fit_method"
      - "params.initial_values"
      - "params.model_bounds"

  metrics:
    cmd: "papermill ${project_paths.stage_metrics} NUL"
    deps:
      - "${project_paths.stage_metrics}"
      - "${dirs.results}"
    metrics:
      - "${dirs.file_pipeline_metrics}"
    plots:
      - "${dirs.plot_new_fit_0}"
      - "${dirs.plot_new_fit_1}"
      - "${dirs.plot_new_fit_2}"
      - "${dirs.plot_error_T_s}"
      - "${dirs.plot_error_q_s}"
      - "${dirs.plot_error_h_a}"
    params:
      - "params.do_plot"

  literature:
    cmd: "python -m boilerdata.stages.literature"
    deps:
      - "${project_paths.stage_literature}"
      - "${dirs.literature}"
      - "${project_paths.models}"
    outs:
      - "${dirs.literature_results}"

  originlab:
    cmd: "python -m boilerdata.stages.originlab"
    deps:
      - "${project_paths.stage_originlab}"
      - "${dirs.results}"
      - "${dirs.literature_results}"
      - "${dirs.plotter}"
    outs:
      - "${dirs.originlab_results}"
    plots:
      - "${dirs.originlab_plot_files.lit}"
      - "${dirs.originlab_plot_files.low}"
