stages:
  schema:
    cmd: "python -m boilerdata.stages.schema"
    params:
      - "config/project.yaml":
    deps:
      - "src/boilerdata/stages/schema.py"
      - "config"
      - "src/boilerdata/models"
    outs:
      - "data/schema"
      # # Can't uncomment this. Deletion breaks schema stage due to cyclic import.
      # - "src/boilerdata/axes_enum.py"

  modelfun:
    cmd: "jupyter execute src/boilerdata/modelfun.ipynb"
    params:
      - "config/project.yaml":
    deps:
      - "src/boilerdata/modelfun.ipynb"
      - "data/schema"
    outs:
      - "data/model"

  runs:
    cmd: "python -m boilerdata.stages.runs"
    params:
      - "config/project.yaml":
    deps:
      - "src/boilerdata/stages/runs.py"
      - "data/schema"
      - "data/curves"
    outs:
      - "data/runs"

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    params:
      - "config/project.yaml":
    deps:
      - "src/boilerdata/stages/pipeline.py"
      - "data/model"
      - "data/runs"
    outs:
      - "data/results"

  plots:
    cmd: "python -m boilerdata.stages.plots"
    params:
      - "config/project.yaml":
    deps:
      - "src/boilerdata/stages/plots.py"
      - "data/results"
    plots:
      - "data/plots/first_new_fit.png"
      - "data/plots/last_new_fit.png"

  literature:
    cmd: "python -m boilerdata.stages.literature"
    params:
      - "config/project.yaml":
    deps:
      - "src/boilerdata/stages/literature.py"
      - "data/schema"
      - "data/literature"
    outs:
      - "data/literature_results"

  originlab:
    cmd: "python -m boilerdata.stages.originlab"
    params:
      - "config/project.yaml":
    deps:
      - "src/boilerdata/stages/originlab.py"
      - "data/results"
      - "data/literature_results"
      - "data/plotter"
    plots:
      - "data/plots/lit_.png"
