stages:
  schema:
    cmd: "python -m boilerdata.stages.schema"
    outs: ["data/schema"]

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    params:
      - "config/axes.yaml":
      - "config/project.yaml":
      - "config/trials.yaml":
    deps:
      - "data/curves"
      - "data/schema"
    outs: ["data/results"]

  originlab:
    cmd: "python -m boilerdata.stages.originlab"
    deps:
      - "data/plotter"
      - "data/results"
    plots: ["data/plots/lit_.png"]
