stages:
  schema:
    cmd: "python -m boilerdata.stages.schema"
    # Track each file directly to avoid a dependency cycle
    deps:
      - "src/boilerdata/stages/schema.py"
      - "src/boilerdata/models/axes.py"
      - "src/boilerdata/models/common.py"
      - "src/boilerdata/models/project.py"
      - "src/boilerdata/models/trials.py"
    outs:
      - "data/schema"
      # # DVC deletes outs before generating. Uncommenting the below breaks it.
      # - "src/boilerdata/models/axes_enum.py"

  runs:
    cmd: "python -m boilerdata.stages.runs"
    params:
      - "config/axes.yaml":
      - "config/project.yaml":
      - "config/trials.yaml":
    deps:
      # Allow other parts of boilerdata to change w/o re-running this stage
      - "src/boilerdata/stages/runs.py"
      - "data/schema"
      - "data/curves"
    outs: ["data/runs"]

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    params:
      - "config/axes.yaml":
      - "config/project.yaml":
      - "config/trials.yaml":
    deps:
      - "src/boilerdata" # Do re-run pipeline if anything in boilerdata changes
      - "data/schema"
      - "data/runs"
    outs: ["data/results"]

  originlab:
    cmd: "python -m boilerdata.stages.originlab"
    deps:
      - "src/boilerdata"
      - "data/plotter"
      - "data/results"
    plots: ["data/plots/lit_.png"]
