stages:
  axes:
    cmd: "echo hello"
  modelfun:
    cmd: "echo hello"
  runs:
    cmd: "echo hello"
  parse_benchmarks:
    cmd: "echo hello"
  pipeline:
    cmd: "echo hello"
  metrics:
    cmd: "echo hello"
  literature:
    cmd: "echo hello"
  originlab:
    cmd: "echo hello"
