stages:
  literature:
    cmd: "python -m boilerdata.stages.literature"
    deps:
      - "config"
      - "src/boilerdata/stages/literature.py"
    # outs:
    #   - "data/literature_results"
    # # Can't uncomment this. Deletion breaks schema stage due to cyclic import.
    # - "src/boilerdata/axes_enum.py"

  schema:
    cmd: "python -m boilerdata.stages.schema"
    params:
      - "config/project.yaml":
    deps:
      - "config"
      - "src/boilerdata/stages/schema.py"
      - "src/boilerdata/models"
    outs:
      - "data/schema"
      # # Can't uncomment this. Deletion breaks schema stage due to cyclic import.
      # - "src/boilerdata/axes_enum.py"

  modelfun:
    cmd: "jupyter execute src/boilerdata/modelfun.ipynb"
    params:
      - "config/project.yaml":
    deps:
      - "config"
      - "src/boilerdata/modelfun.ipynb"
      - "src/boilerdata/models"
      - "data/schema"
    outs:
      - "data/model"

  runs:
    cmd: "python -m boilerdata.stages.runs"
    params:
      - "config/project.yaml":
    deps:
      - "config"
      - "src/boilerdata/stages/runs.py"
      - "src/boilerdata/models"
      - "data/schema"
      - "data/curves"
    outs: ["data/runs"]

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    params:
      - "config/project.yaml":
    deps:
      - "config"
      - "src/boilerdata" # Do re-run pipeline if anything in boilerdata changes
      - "src/boilerdata/models"
      - "data/schema"
      - "data/model"
      - "data/runs"
    outs: ["data/results"]
    plots:
      - "data/plots/first_new_fit.png"
      - "data/plots/last_new_fit.png"

  originlab:
    cmd: "python -m boilerdata.stages.originlab"
    params:
      - "config/project.yaml":
    deps:
      - "config"
      - "src/boilerdata"
      - "data/plotter"
      - "data/results"
    plots: ["data/plots/lit_.png"]
