stages:
  schema:
    cmd: "python -m boilerdata.stages.schema"
    deps:
      - "${dirs.stages}/schema.py"
      - "${dirs.config}"
      - "${dirs.models}"
    outs:
      - "${dirs.project_schema}"
      # # Can't uncomment this. Deletion breaks schema stage due to cyclic import.
      # - "src/boilerdata/axes_enum.py"

  modelfun:
    cmd: "jupyter execute ${dirs.stages}/modelfun.ipynb"
    deps:
      - "${dirs.stages}/modelfun.ipynb"
      - "${dirs.project_schema}"
    outs:
      - "${dirs.modelfun}"

  runs:
    cmd: "python -m boilerdata.stages.runs"
    deps:
      - "${dirs.stages}/runs.py"
      - "${dirs.project_schema}"
      - "${dirs.trials}"
    outs:
      - "${dirs.runs}"

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    deps:
      - "${dirs.stages}/pipeline.py"
      - "${dirs.modelfun}"
      - "${dirs.runs}"
    outs:
      - "${dirs.results}"

  metrics:
    cmd: "python -m boilerdata.stages.metrics"
    deps:
      - "${dirs.stages}/metrics.py"
      - "${dirs.results}"
    outs:
      - "${dirs.new_fits}"
    metrics:
      - "${dirs.file_pipeline_metrics}"
    plots:
      - "${dirs.file_pipeline_metrics_plot}"
      - "${dirs.metrics}/first_new_fit.png"
      - "${dirs.metrics}/last_new_fit.png"

  literature:
    cmd: "python -m boilerdata.stages.literature"
    deps:
      - "${dirs.stages}/literature.py"
      - "${dirs.project_schema}"
      - "${dirs.literature}"
    outs:
      - "${dirs.literature_results}"

  originlab:
    cmd: "python -m boilerdata.stages.originlab"
    deps:
      - "${dirs.stages}/originlab.py"
      - "${dirs.results}"
      - "${dirs.literature_results}"
      - "${dirs.plotter}"
    outs:
      - "${dirs.originlab_results}"
    plots:
      - "${dirs.metrics}/lit_.png"
