stages:
  update_schema:
    cmd: "python -m boilerdata.stages.schema"
    outs:
      - "data/schema"

  pipeline:
    cmd: "python -m boilerdata.stages.pipeline"
    deps:
      - "data/schema"
      - "data/curves"
    params:
      - "config/axes.yaml":
      - "config/project.yaml":
      - "config/trials.yaml":
    outs: ["data/results"]

  plot:
    cmd: "python -m boilerdata.plot"
    deps:
      - "data/plotter"
      - "data/results"
    plots: ["data/plots/lit_.png"]
