params:
  do_plot: true

  records_to_average: 9

  water_temps:
    - T_w1
    - T_w2
    - T_w3

  model_inputs:
    r: 0.0047625
    T_infa: 25
    T_infw: 100
    x_s: 0
    x_wa: 0.0381

  model_params:
    - T_s
    - q_s
    - k
    - h_a
    - h_w

  fixed_params:
    - k
    - h_w

  initial_values:
    T_s: 95
    q_s: 0
    k: 400
    h_a: 0
    h_w: 0

  model_bounds:
    T_s: [95, inf]
    q_s: [0, inf]
    k: [350, 450]
    h_a: [0, inf]
    h_w: [0, inf]
dirs:
  base: .
  file_proj: params.yaml
  config: config
  package: src/boilerdata
  stages: src/boilerdata/stages
  models: src/boilerdata/models
  validation: src/boilerdata/validation.py
  data: data
  axes: data/axes
  file_originlab_coldes: data/axes/originlab_coldes.txt
  project_schema: data/schema
  literature: data/literature
  literature_results: data/literature_results
  file_literature_results: data/literature_results/lit.csv
  modelfun: data/modelfun
  file_model: data/modelfun/model.dillpickle
  trials: data/curves
  runs: data/runs
  file_runs: data/runs/runs.csv
  results: data/results
  file_results: data/results/results.csv
  plotter: data/plotter
  file_plotter: data/plotter/results.opju
  originlab_results: data/originlab_results
  file_originlab_results: data/originlab_results/originlab_results.csv
  metrics: data/metrics
  file_new_fit_0: data/metrics/new_fit_0.png
  file_new_fit_1: data/metrics/new_fit_1.png
  file_new_fit_2: data/metrics/new_fit_2.png
  new_fits: data/metrics/new_fits
  file_pipeline_metrics_plot: data/metrics/pipeline_metrics.png
  file_pipeline_metrics: data/metrics/pipeline_metrics.json
  file_axes_enum: C:/Users/Blake/Code/mine/boilerdata/src/boilerdata/axes_enum.py
  stage_setup: src/boilerdata/stages/setup.py
  stage_axes: src/boilerdata/stages/axes.py
  stage_literature: src/boilerdata/stages/literature.py
  stage_metrics: src/boilerdata/stages/metrics.py
  stage_modelfun: src/boilerdata/stages/modelfun.ipynb
  stage_originlab: src/boilerdata/stages/originlab.py
  stage_pipeline: src/boilerdata/stages/pipeline.py
  stage_runs: src/boilerdata/stages/runs.py
  stage_schema: src/boilerdata/stages/schema.py
  file_axes_enum_copy: data/axes/axes_enum.py
