# When deleting and regenerating "dirs", swap "\" for "/" to avoid DVC plot issues.
dirs:
  file_axes_enum: C:\Users\Blake\Code\mine\boilerdata\src\boilerdata\axes_enum.py
  base: .
  config: config

  package: src\boilerdata
  stages: src\boilerdata\stages
  models: src\boilerdata\models

  data: data

  project_schema: data\schema
  file_originlab_coldes: data\schema\originlab_coldes.txt

  literature: data\literature
  literature_results: data\literature_results
  file_literature_results: data\literature_results\lit.csv

  modelfun: data\modelfun
  file_model: data\modelfun\model.dillpickle

  trials: data\curves
  runs: data\runs
  file_runs: data\runs\runs.csv

  results: data\results
  file_results: data\results\results.csv

  plotter: data\plotter
  file_plotter: data\plotter\results.opju
  originlab_results: data\originlab_results
  file_originlab_results: data\originlab_results\originlab_results.csv

  metrics: data\metrics
  new_fits: data\metrics\new_fits
  file_pipeline_metrics_plot: data\metrics\pipeline_metrics.png
  file_pipeline_metrics: data\metrics\pipeline_metrics.json

geometry:
  diameter: 0.375

  rods:
    W: [3.5250, 3.0500, 2.5750, 2.1000, 0.3750]
    X: [3.5253, 3.0500, 2.5756, 2.1006, 0.3754]
    Y: [3.5250, 3.0504, 2.5752, 2.1008, 0.3752]
    R: [4.1000, 3.6250, 3.1500, 2.6750, 0.9500]

  coupons:
    A0: 0.000
    A1: 0.766
    A2: 0.770
    A3: 0.769
    A4: 0.746
    A5: 0.734
    A6: 0.750
    A7: 0.753
    A8: 0.753
    A9: 0.553

params:
  records_to_average: 9
  do_plot: true
