params:
  do_plot: true
  records_to_average: 9
  fit_method: trf
  water_temps:
    - T_w1
    - T_w2
    - T_w3
  model_inputs:
    r: 0.0047625
    T_infa: 25
    T_infw: 100
    x_s: 0
    x_wa: 0.0381
  model_params:
    - T_s
    - q_s
    - k
    - h_a
    - h_w
  fixed_params:
    - k
    - h_w
  initial_values:
    T_s: 95
    q_s: 0
    k: 400
    h_a: 0
    h_w: 0
  model_bounds:
    T_s:
      - -inf
      - inf
    q_s:
      - -inf
      - inf
    k:
      - 350
      - 450
    h_a:
      - -inf
      - inf
    h_w:
      - -inf
      - inf
dirs:
  base: .
  file_proj: params.yaml
  config: config
  package: src/boilerdata
  stages: src/boilerdata/stages
  notebooks: src/boilerdata/stages/notebooks
  models: src/boilerdata/models
  validation: src/boilerdata/validation.py
  file_axes_enum: src/boilerdata/axes_enum.py
  data: data
  axes: data/axes
  file_originlab_coldes: data/axes/originlab_coldes.txt
  project_schema: data/schema
  literature: data/literature
  literature_results: data/literature_results
  file_literature_results: data/literature_results/lit.csv
  modelfun: data/modelfun
  file_model: data/modelfun/model.dillpickle
  trials: data/curves
  runs: data/runs
  file_runs: data/runs/runs.csv
  results: data/results
  file_results: data/results/results.csv
  plotter: data/plotter
  file_plotter: data/plotter/results.opju
  originlab_results: data/originlab_results
  file_originlab_results: data/originlab_results/originlab_results.csv
  plot_config: config/plotting
  mpl_base: config/plotting/base.mplstyle
  mpl_hide_title: config/plotting/hide_title.mplstyle
  metrics: data/metrics
  plots: data/metrics/plots
  plot_new_fit_0: data/metrics/plots/new_fit_0.svg
  plot_new_fit_1: data/metrics/plots/new_fit_1.svg
  plot_new_fit_2: data/metrics/plots/new_fit_2.svg
  plot_error_T_s: data/metrics/plots/error_T_s.svg
  plot_error_q_s: data/metrics/plots/error_q_s.svg
  plot_error_h_a: data/metrics/plots/error_h_a.svg
  originlab_plots: data/metrics/originlab_plots
  originlab_plot_files:
    lit: data/metrics/originlab_plots/lit.svg
    low: data/metrics/originlab_plots/low.svg
  tables: data/metrics/tables
  file_pipeline_metrics: data/metrics/tables/pipeline_metrics.json
  stage_setup: src/boilerdata/stages/setup.py
  stage_axes: src/boilerdata/stages/axes.py
  stage_literature: src/boilerdata/stages/literature.py
  stage_metrics: src/boilerdata/stages/notebooks/metrics.ipynb
  stage_modelfun: src/boilerdata/stages/notebooks/modelfun.ipynb
  stage_originlab: src/boilerdata/stages/originlab.py
  stage_pipeline: src/boilerdata/stages/pipeline.py
  stage_runs: src/boilerdata/stages/runs.py
  stage_schema: src/boilerdata/stages/schema.py
  file_axes_enum_copy: data/axes/axes_enum.py
