params:
  do_plot: true
  records_to_average: 9

  initial_values:
    T_s: 95
    q_s: 0
    k: 400
    h_a: 0
    h_w: 0

  model_bounds:
    T_s: [95, inf]
    q_s: [0, inf]
    k: [350, 450]
    h_a: [0, inf]
    h_w: [0, inf]

dirs:
  base: .
  config: config

  package: src/boilerdata
  stages: src/boilerdata/stages
  models: src/boilerdata/models

  data: data

  project_schema: data/schema
  file_originlab_coldes: data/schema/originlab_coldes.txt

  literature: data/literature
  literature_results: data/literature_results

  modelfun: data/modelfun

  trials: data/curves
  runs: data/runs

  results: data/results

  plotter: data/plotter
  originlab_results: data/originlab_results

  metrics: data/metrics
  new_fits: data/metrics/new_fits
  file_pipeline_metrics_plot: data/metrics/pipeline_metrics.png
  file_pipeline_metrics: data/metrics/pipeline_metrics.json
