[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilerdata"
requires-python = ">=3.10"
dependencies = [ "dvc[gs]~=2.29.0", "matplotlib~=3.6.0", "originpro~=1.1.2", "pandas-stubs~=1.5.0.220926", "pandas~=1.5.0", "pandera~=0.12.0", "pyarrow~=9.0.0", "pydantic~=1.10.1", "pyyaml~=6.0", "scipy~=1.9.1",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilerdata@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilerdata"

[project.scripts]
boilerdata = "boilerdata.__main__:app"

[project.optional-dependencies]
