[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilerdata"
requires-python = ">=3.10"
dependencies = [ "dill~=0.3.6", "dvc[gs]~=2.38.0", "matplotlib~=3.6.0", "originpro~=1.1.2", "pandas~=1.5.0", "pandera~=0.13.1", "papermill~=2.4.0", "propshop~=0.0.10", "pyarrow~=10.0.0", "pydantic~=1.10.1", "pyjanitor~=0.24.0", "pyXSteam~=0.4.9", "pyyaml~=6.0", "ruamel.yaml~=0.17.21", "seaborn~=0.12.1", "scipy~=1.9.1", "sympy~=1.11.1", "uncertainties~=3.1.7",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilerdata@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilerdata"

[project.scripts]
boilerdata = "boilerdata.__main__:app"

[project.optional-dependencies]
