[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilerdata"
requires-python = ">=3.10"
dependencies = [ "dvc[gs]~=2.31.0", "matplotlib~=3.6.0", "nbclient~=0.7.0", "originpro~=1.1.2", "pandas~=1.5.0", "pandera~=0.13.1", "pyarrow~=9.0.0", "pydantic~=1.10.1", "pyjanitor~=0.23.1", "pyXSteam~=0.4.9", "pyyaml~=6.0", "scipy~=1.9.1", "uncertainties~=3.1.7",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilerdata@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilerdata"

[project.scripts]
boilerdata = "boilerdata.__main__:app"

[project.optional-dependencies]
