[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilerdata"
requires-python = ">=3.10"
dependencies = [ "propshop~=0.0.2", "dynaconf~=3.1.8", "pydantic~=1.9.0", "pandas~=1.4.2", "pandas-stubs~=1.2.0.58", "openpyxl~=3.0.9", "pyarrow~=7.0.0", "scipy~=1.8.0", "matplotlib~=3.5.2", "PyQt6~=6.3.0", "fire~=0.4.0", "rich~=12.3.0",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilerdata@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilerdata"

[project.scripts]
boilerdata = "boilerdata.cli:main"

[project.optional-dependencies]
