all:
  - name: "trial"
    dtype: "datetime64[ns]"
    index: true

  - name: "run"
    dtype: "datetime64[ns]"
    index: true

  - name: "time"
    dtype: "datetime64[ns]"
    source: "time"
    index: true
    originlab_coldes: Q # Dropped after averaging

  - name: "group"
    dtype: "category"
    meta: true

  - name: "rod"
    dtype: "category"
    meta: true

  - name: "coupon"
    dtype: "category"
    meta: true

  - name: "sample"
    dtype: "category"
    meta: true

  - name: "joint"
    dtype: "category"
    meta: true

  - name: "sixth_tc"
    pretty_name: sixth-tc # Avoid underscore-subscript conversion
    dtype: "boolean"
    meta: true

  - name: "good"
    dtype: "boolean"
    meta: true

  - name: "new"
    dtype: "boolean"
    meta: true

  - name: "V"
    units: "V"
    source: "V"

  - name: "I"
    units: "A"
    source: "I"

  - name: "T_0"
    units: "C"
    source: "T0cal"

  - name: "T_1"
    units: "C"
    source: "T1cal"

  - name: "T_2"
    units: "C"
    source: "T2cal"

  - name: "T_3"
    units: "C"
    source: "T3cal"

  - name: "T_4"
    units: "C"
    source: "T4cal"

  - name: "T_5"
    units: "C"
    source: "T5cal"

  - name: "T_6"
    units: "C"
    source: "T6cal"

  - name: "T_w1"
    units: "C"
    source: "Tw1cal"

  - name: "T_w2"
    units: "C"
    source: "Tw2cal"

  - name: "T_w3"
    units: "C"
    source: "Tw3cal"

  - name: "P"
    units: "psi"
    source: "Pcal"

  - name: "T_w"
    units: "C"

  - name: "T_w_diff"
    units: "C"

  - name: "a"
    units: "K"

  - name: "b"
    units: "K"

  - name: "c"
    units: "K"

  - name: "dT_dx"
    units: "K"

  - name: "dT_dx_err"
    units: "K"

  - name: "T_s"
    units: "C"

  - name: "T_s_err"
    units: "C"

  - name: "k"
    units: "W/m-K"

  - name: "q"
    pretty_name: "q''"
    units: "W/cm^2"
    originlab_coldes: "Y"

  - name: "q_err"
    pretty_name: "q''_err"
    units: "W/cm^2"
    originlab_coldes: "E"

  - name: "Q"
    units: "W"

  - name: "DT"
    pretty_name: "∆T"
    units: "K"
    originlab_coldes: "X"

  - name: "DT_err"
    pretty_name: "∆T_err"
    units: "K"
    originlab_coldes: "M"
