data_path: G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data/Boiling Curves/22.01.19 Copper X-A6-B3-1/data2

fit:
  thermocouple_pos: # (m) Post X
    - 0.00000000
    - 0.01207262
    - 0.02412238
    - 0.03618738
    - 0.08000746
  post_length: 0.10859262 # (m) Distance from T1 to end of Post X plus sample A6
  do_plot: false
