data_path: G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data/Test Runs/22.04.08 Copper X-A9-newcam/data

# data_path: G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data/Boiling Curves/22.03.29 Copper X-A6-1/data

# data_path: G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data/Boiling Curves/21.12.09 Copper Y-A7-1/data

# data_path: G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data/Boiling Curves/22.01.06 Copper Y-A7-2/data

# data_path: G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data/Boiling Curves/22.01.19 Copper X-A6-B3-1/data

# ! Also used for Y-A7-1 and Y-A7-2 trials! Need to fix this when expanding this to multiple directories
fit:
  # # (m) Distance for X-A9, but with artificially reduced "quasi" length
  # thermocouple_pos:
  #   - 0.09954262
  #   - 0.08747
  #   - 0.07542024
  #   - 0.06335524
  #   - 0.01953516
  # do_plot: false

  # New sample
  # (m) Distance from thermocouples to end of Post X plus sample A9
  thermocouple_pos:
    - 0.10358882
    - 0.0915162
    - 0.07946644
    - 0.06740144
    - 0.02358136
  do_plot: true

  # # AFTER polishing removed ~0.0017m of material from A6
  # # (m) Distance from thermocouples to end of Post X plus sample A6
  # thermocouple_pos:
  #   - -0.10689262
  #   - -0.09482
  #   - -0.08277024
  #   - -0.07070524
  #   - -0.02688516
  # do_plot: true

  # # Before polishing removed ~0.0017m of material
  # # (m) Distance from thermocouples to end of Post X plus sample A6
  # thermocouple_pos:
  #   - -0.10859262
  #   - -0.09652000
  #   - -0.08447024
  #   - -0.07240524
  #   - -0.02858516
  # do_plot: true

  # Old values
  # thermocouple_pos:
  #   - 0.00000000
  #   - 0.01207262
  #   - 0.02412238
  #   - 0.03618738
  #   - 0.08000746
  # post_length: 0.10859262
