data_path: G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data/Boiling Curves/22.01.19 Copper X-A6-B3-1/data2

fit:
  x: # (m) Post X
    - 0.00000000
    - 0.01207262
    - 0.02412238
    - 0.03618738
    - 0.08000746
  T_p_str:
    - T1cal (C)
    - T2cal (C)
    - T3cal (C)
    - T4cal (C)
    - T5cal (C)
  material: Copper
  k: k (W/m-K)
  T_b_str: T1fit (C)
  T_L_str: T_CuSS (C)
  slope: dTdx (K/m)
  L: 0.10859262 # (m) Length of post X plus A6
  D: 0.009525 # (m) 3/8"
  do_plot: true
