columns:
  V:
    units: "V"
  I:
    units: "A"
  T0:
    units: "C"
  T1:
    units: "C"
  T2:
    units: "C"
  T3:
    units: "C"
  T4:
    units: "C"
  T5:
    units: "C"
  Tw1:
    units: "C"
  Tw2:
    units: "C"
  Tw3:
    units: "C"
  P:
    units: "V"
  T0cal:
    units: "C"
  T1cal:
    units: "C"
  T2cal:
    units: "C"
  T3cal:
    units: "C"
  T4cal:
    units: "C"
  T5cal:
    units: "C"
  Tw1cal:
    units: "C"
  Tw2cal:
    units: "C"
  Tw3cal:
    units: "C"
  Pcal:
    units: "psi"
  Q01:
    units: "W"
  Q12:
    units: "W"
  Q23:
    units: "W"
  Q34:
    units: "W"
  Q45:
    units: "W"
  T6ext:
    units: "C"
  dT_dx:
    units: "K/m"
  TLfit:
    units: "C"
  rvalue:
    units: ""
  pvalue:
    units: ""
  stderr:
    units: ""
  intercept_stderr:
    units: ""
  dT_dx_err:
    units: "K/m"
  k:
    units: "W/m-K"
  q:
    units: "W/cm^2"
    originlab_column_designation: "Y"
  q_err:
    units: "W/cm^2"
    originlab_column_designation: "E"
  Q:
    units: "W"
  DT:
    pretty_name: ∆T
    units: "K"
    originlab_column_designation: "X"
  DT_err:
    pretty_name: ∆T_err
    units: "K"
    originlab_column_designation: "M"
  date:
    units: ""
  rod:
    units: ""
  coupon:
    units: ""
  sample:
    units: ""
  group:
    units: ""
  joint:
    units: ""
  monotonic:
    units: ""
  comment:
    units: ""
