columns:
- label: V
  units: V
- label: I
  units: A
- label: T0
  units: C
- label: T1
  units: C
- label: T2
  units: C
- label: T3
  units: C
- label: T4
  units: C
- label: T5
  units: C
- label: Tw1
  units: C
- label: Tw2
  units: C
- label: Tw3
  units: C
- label: P
  units: V
- label: T0cal
  units: C
- label: T1cal
  units: C
- label: T2cal
  units: C
- label: T3cal
  units: C
- label: T4cal
  units: C
- label: T5cal
  units: C
- label: Tw1cal
  units: C
- label: Tw2cal
  units: C
- label: Tw3cal
  units: C
- label: Pcal
  units: psi
- label: Q01
  units: W
- label: Q12
  units: W
- label: Q23
  units: W
- label: Q34
  units: W
- label: Q45
  units: W
- label: T6ext
  units: C
- label: dT/dx
  units: K/m
- label: TLfit
  units: C
- label: rvalue
  units: ''
- label: pvalue
  units: ''
- label: stderr
  units: ''
- label: intercept_stderr
  units: ''
- label: dT/dx_err
  units: K/m
- label: k
  units: W/m-K
- label: q
  units: W/m^2
- label: q_err
  units: W/m^2
- label: Q
  units: W
- label: "\u2206T"
  units: K
- label: "\u2206T_err"
  units: K
- label: q_dupe
  units: W/cm^2
- label: q_err_dupe
  units: W/cm^2
- label: date
  units: ''
- label: rod
  units: ''
- label: coupon
  units: ''
- label: sample
  units: ''
- label: group
  units: ''
- label: monotonic
  units: ''
- label: joint
  units: ''
- label: comment
  units: ''
