cols:
  run:
    dtype: string
    source: "time"
    index: true
  V:
    units: "V"
    source: "V"
  I:
    units: "A"
    source: "I"
  T_0:
    units: "C"
    source: "T0cal"
  T_1:
    units: "C"
    source: "T1cal"
  T_2:
    units: "C"
    source: "T2cal"
  T_3:
    units: "C"
    source: "T3cal"
  T_4:
    units: "C"
    source: "T4cal"
  T_5:
    units: "C"
    source: "T5cal"
  T_w1:
    units: "C"
    source: "Tw1cal"
  T_w2:
    units: "C"
    source: "Tw2cal"
  T_w3:
    units: "C"
    source: "Tw3cal"
  P:
    units: "psi"
    source: "Pcal"
  dT_dx:
    units: "K/m"
  TLfit:
    units: "C"
  rvalue: {}
  pvalue: {}
  stderr: {}
  intercept_stderr: {}
  dT_dx_err:
    units: "K/m"
  k:
    units: "W/m-K"
  q:
    units: "W/cm^2"
    originlab_coldes: "Y"
  q_err:
    units: "W/cm^2"
    originlab_coldes: "E"
  Q:
    units: "W"
  DT:
    pretty_name: "∆T"
    units: "K"
    originlab_coldes: "X"
  DT_err:
    pretty_name: "∆T_err"
    units: "K"
    originlab_coldes: "M"
  date:
    dtype: datetime64[ns]
  rod:
    dtype: category
  coupon:
    dtype: category
  sample:
    dtype: category
  group:
    dtype: category
  joint:
    dtype: category
  monotonic:
    dtype: category
  comment:
    dtype: category
