#:schema https://raw.githubusercontent.com/blakeNaccarato/boilerdata/blob/main/project/schema/old_schema.json

data = "."

[fit]
thermocouple_pos = [0.10358882, 0.0915162, 0.07946644, 0.06740144, 0.02358136]
do_plot = false
