#:schema https://raw.githubusercontent.com/blakeNaccarato/boilerdata/main/project/schema/old_schema.json

trials = "G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data"

data = "data"
