dirs:
  base: "G:/My Drive/Blake/School/Grad/Projects/18.09 Nucleate Pool Boiling/Data"
  config: "~/Code/mine/boilerdata/project/config"
  project_schema: "~/Code/mine/boilerdata/project/schema"
  trials: "Boiling Curves"
  results: "Results"
  per_trial: "data"

geometry:
  rods:
    W: [3.5250, 3.0500, 2.5750, 2.1000, 0.3750]
    X: [3.5253, 3.0500, 2.5756, 2.1006, 0.3754]
    Y: [3.5250, 3.0504, 2.5752, 2.1008, 0.3752]

  coupons:
    A1: 0.766
    A2: 0.770
    A3: 0.769
    A4: 0.746
    A5: 0.734
    A6: 0.750
    A7: 0.753
    A8: 0.753
    A9: 0.553

params: {}

fit:
  # Corresponds with X A9
  thermocouple_pos:
    - 0.10358882
    - 0.0915162
    - 0.07946644
    - 0.06740144
    - 0.02358136
  do_plot: false
# Introduce post dimensions to be referenced in `trials.yaml`. For "No T5" modified post W, use different post definition for that. Mapping assumes T1 and up associated with post dimensions. Need sample lengths as well, then a position calculator.
