name: "main"

on: ["push", "workflow_dispatch"]

jobs:
  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  bump_project:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.10"
          install-project: false
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Bump project template and compose `pyproject.toml`."
  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.10"
      - run: "pyright"
  pytest-cov:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.10"
      - uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: "projects/326920613558/locations/global/workloadIdentityPools/github-com/providers/github-com-oidc"
          service_account: "iterative-studio@secure-garden-355020.iam.gserviceaccount.com"
      - uses: "google-github-actions/setup-gcloud@v1.1.0"
      - run: "dvc pull"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: "pytest --cov"
        env:
          OPENCV_SAMPLES_DATA_PATH: data/samples_data
      - uses: "codecov/codecov-action@v3.1.1"

  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.
