name: "main"

on: ["push", "workflow_dispatch"]

jobs:
  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.10"
      - run: "pyright"
  ruff:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.10"
      - run: "ruff --no-fix --format github ."
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.10"
      - run: "pytest"
      - uses: "codecov/codecov-action@v3.1.3"
  bump_project:
    needs: ["pyright", "ruff", "pytest"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.10"
          install-project: false
      - uses: "stefanzweifel/git-auto-commit-action@v4.16.0"
        with:
          commit_message: "Bump project template and compose `pyproject.toml`."

  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.
